export interface GetCarInfo {
bodyTypeCode: "5",
bodyTypeDescAr: "سيارة صغيرة 4 باب",
capacity: "7",
cylinder: "8",
majorColor: "احمر",
make: "اودي",
makeCode: "30",
model: " كيو 7",
modelCode: "6",
modelYear: "2022",
plateNumber: "1452",
plateText1: "ح",
plateText2: "ص",
plateText3: "د",
regTypeCode: "1",
regTypeDescAr: "خاص",
registrationExpiryDate: "14451225",
registrationLocationCode: "1000",
registrationLocationDescAr: "مركز المعلومات",
vehicleClassCode: "2",
vehicleClassDescAr: "سيارة ركوب",
vehicleIDNumber: "HSDAW1254",
weight: "6",
}
